[package]
name = "april-core"
version = "0.1.0"
authors = ["Tanmoy Paul"]
description = "April core components"
readme = "README.md"
repository = "https://github.com/paultanmoy/april-core.git"
license = "GPLv3"
edition = "2021"

[dependencies]
serde_json = "1.0.127"
thiserror = "1.0.63"
